USE railway;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(150) UNIQUE,
  password VARCHAR(255),
  role ENUM('user','admin') DEFAULT 'user',
  fine_count INT DEFAULT 0
);

CREATE TABLE books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200),
  author VARCHAR(150),
  genre VARCHAR(80),
  total_copies INT DEFAULT 1,
  available_copies INT DEFAULT 1
);

CREATE TABLE transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  book_id INT,
  borrow_date DATE,
  due_date DATE,
  return_date DATE,
  status ENUM('pending','borrowed','returned','rejected') DEFAULT 'pending',
  fine_applied TINYINT DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

CREATE TABLE book_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  title VARCHAR(200) NOT NULL,
  author VARCHAR(150),
  request_date DATE,
  status ENUM('pending','approved','rejected') DEFAULT 'pending',
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Insert an admin user: password is 'admin123'
INSERT INTO users (name, email, password, role) VALUES ('Admin', 'admin@shelf.com', 'scrypt:32768:8:1$prSGa4uTzl6xD8to$53fe3282cb004be65bd6d6b6d14b097cbcfb47f3842218cf1ea4f99c7659846dffb5a15d743c01a710490787409f7853065c7f167787d7e34e9294469f02a5fe', 'admin');

-- Insert some dummy books
INSERT INTO books (title, author, genre, total_copies, available_copies) VALUES 
-- Your Corrected Initial List
('The Catcher in the Rye', 'J.D. Salinger', 'Fiction', 3, 3),
('To Kill a Mockingbird', 'Harper Lee', 'Classic', 5, 5),
('1984', 'George Orwell', 'Dystopian', 2, 2),
('The Great Gatsby', 'F. Scott Fitzgerald', 'Classic', 4, 4),
('Moby-Dick', 'Herman Melville', 'Classic', 1, 1),
('Pride and Prejudice', 'Jane Austen', 'Romance', 3, 3),

-- Classics & Literature
('Catch-22', 'Joseph Heller', 'Classic', 4, 4),
('The Grapes of Wrath', 'John Steinbeck', 'Classic', 3, 3),
('Lord of the Flies', 'William Golding', 'Classic', 5, 5),
('Animal Farm', 'George Orwell', 'Classic', 6, 6),
('Brave New World', 'Aldous Huxley', 'Dystopian', 4, 4),
('Fahrenheit 451', 'Ray Bradbury', 'Dystopian', 5, 5),
('The Bell Jar', 'Sylvia Plath', 'Fiction', 2, 2),
('The Picture of Dorian Gray', 'Oscar Wilde', 'Classic', 3, 3),
('Frankenstein', 'Mary Shelley', 'Sci-Fi', 4, 4),
('Dracula', 'Bram Stoker', 'Horror', 3, 3),
('Jane Eyre', 'Charlotte Brontë', 'Classic', 4, 4),
('Wuthering Heights', 'Emily Brontë', 'Classic', 2, 2),
('Great Expectations', 'Charles Dickens', 'Classic', 5, 5),
('Crime and Punishment', 'Fyodor Dostoevsky', 'Classic', 3, 3),
('The Odyssey', 'Homer', 'Epic', 2, 2),
('The Iliad', 'Homer', 'Epic', 2, 2),
('Don Quixote', 'Miguel de Cervantes', 'Classic', 1, 1),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'Classic', 2, 2),
('Anna Karenina', 'Leo Tolstoy', 'Classic', 3, 3),
('War and Peace', 'Leo Tolstoy', 'Historical Fiction', 1, 1),
('Les Misérables', 'Victor Hugo', 'Historical Fiction', 2, 2),
('The Count of Monte Cristo', 'Alexandre Dumas', 'Adventure', 4, 4),
('A Tale of Two Cities', 'Charles Dickens', 'Historical Fiction', 3, 3),
('The Stranger', 'Albert Camus', 'Philosophical Fiction', 4, 4),
('The Metamorphosis', 'Franz Kafka', 'Fiction', 5, 5),

-- Science Fiction
('Dune', 'Frank Herbert', 'Sci-Fi', 6, 6),
('Foundation', 'Isaac Asimov', 'Sci-Fi', 4, 4),
('Neuromancer', 'William Gibson', 'Sci-Fi', 3, 3),
('Snow Crash', 'Neal Stephenson', 'Sci-Fi', 2, 2),
('The Martian', 'Andy Weir', 'Sci-Fi', 5, 5),
('Project Hail Mary', 'Andy Weir', 'Sci-Fi', 4, 4),
('The Three-Body Problem', 'Liu Cixin', 'Sci-Fi', 3, 3),
('I, Robot', 'Isaac Asimov', 'Sci-Fi', 4, 4),
('Ender''s Game', 'Orson Scott Card', 'Sci-Fi', 5, 5),
('The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 'Sci-Fi', 6, 6),
('The Left Hand of Darkness', 'Ursula K. Le Guin', 'Sci-Fi', 2, 2),
('Hyperion', 'Dan Simmons', 'Sci-Fi', 3, 3),
('Ringworld', 'Larry Niven', 'Sci-Fi', 2, 2),
('Stranger in a Strange Land', 'Robert A. Heinlein', 'Sci-Fi', 3, 3),
('Do Androids Dream of Electric Sheep?', 'Philip K. Dick', 'Sci-Fi', 4, 4),
('Altered Carbon', 'Richard K. Morgan', 'Sci-Fi', 2, 2),
('Leviathan Wakes', 'James S.A. Corey', 'Sci-Fi', 4, 4),
('Dark Matter', 'Blake Crouch', 'Sci-Fi', 3, 3),
('Recursion', 'Blake Crouch', 'Sci-Fi', 2, 2),
('Jurassic Park', 'Michael Crichton', 'Sci-Fi', 5, 5),

-- Fantasy
('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 5, 5),
('The Fellowship of the Ring', 'J.R.R. Tolkien', 'Fantasy', 4, 4),
('The Two Towers', 'J.R.R. Tolkien', 'Fantasy', 4, 4),
('The Return of the King', 'J.R.R. Tolkien', 'Fantasy', 4, 4),
('The Name of the Wind', 'Patrick Rothfuss', 'Fantasy', 3, 3),
('Mistborn: The Final Empire', 'Brandon Sanderson', 'Fantasy', 5, 5),
('The Way of Kings', 'Brandon Sanderson', 'Fantasy', 4, 4),
('A Game of Thrones', 'George R.R. Martin', 'Fantasy', 6, 6),
('A Clash of Kings', 'George R.R. Martin', 'Fantasy', 4, 4),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy', 7, 7),
('Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 'Fantasy', 5, 5),
('Harry Potter and the Prisoner of Azkaban', 'J.K. Rowling', 'Fantasy', 5, 5),
('The Color of Magic', 'Terry Pratchett', 'Fantasy', 3, 3),
('Good Omens', 'Terry Pratchett & Neil Gaiman', 'Fantasy', 4, 4),
('American Gods', 'Neil Gaiman', 'Fantasy', 3, 3),
('The Lies of Locke Lamora', 'Scott Lynch', 'Fantasy', 2, 2),
('The Blade Itself', 'Joe Abercrombie', 'Fantasy', 3, 3),
('Eragon', 'Christopher Paolini', 'Fantasy', 4, 4),
('The Golden Compass', 'Philip Pullman', 'Fantasy', 4, 4),
('Assassin''s Apprentice', 'Robin Hobb', 'Fantasy', 2, 2),

-- Philosophy & Psychology
('Meditations', 'Marcus Aurelius', 'Philosophy', 5, 5),
('Beyond Good and Evil', 'Friedrich Nietzsche', 'Philosophy', 2, 2),
('The Republic', 'Plato', 'Philosophy', 3, 3),
('Man''s Search for Meaning', 'Viktor E. Frankl', 'Psychology', 6, 6),
('Thinking, Fast and Slow', 'Daniel Kahneman', 'Psychology', 4, 4),
('The Prince', 'Niccolò Machiavelli', 'Philosophy', 3, 3),
('The Art of War', 'Sun Tzu', 'Philosophy', 5, 5),
('Critique of Pure Reason', 'Immanuel Kant', 'Philosophy', 1, 1),
('Being and Nothingness', 'Jean-Paul Sartre', 'Philosophy', 1, 1),
('The Myth of Sisyphus', 'Albert Camus', 'Philosophy', 3, 3),
('Thus Spoke Zarathustra', 'Friedrich Nietzsche', 'Philosophy', 2, 2),
('Nicomachean Ethics', 'Aristotle', 'Philosophy', 2, 2),
('Symposium', 'Plato', 'Philosophy', 2, 2),
('Tao Te Ching', 'Laozi', 'Philosophy', 4, 4),
('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 'Non-Fiction', 6, 6),
('Blink', 'Malcolm Gladwell', 'Psychology', 3, 3),
('Outliers', 'Malcolm Gladwell', 'Psychology', 4, 4),
('Quiet', 'Susan Cain', 'Psychology', 3, 3),
('Flow: The Psychology of Optimal Experience', 'Mihaly Csikszentmihalyi', 'Psychology', 2, 2),
('The Power of Habit', 'Charles Duhigg', 'Psychology', 5, 5),
('Atomic Habits', 'James Clear', 'Psychology', 8, 8),
('Mindset', 'Carol S. Dweck', 'Psychology', 4, 4),
('Influence: The Psychology of Persuasion', 'Robert B. Cialdini', 'Psychology', 3, 3),
('Predictably Irrational', 'Dan Ariely', 'Psychology', 3, 3),
('The Body Keeps the Score', 'Bessel van der Kolk', 'Psychology', 5, 5),

-- Computer Science & Technology
('Clean Code', 'Robert C. Martin', 'Technology', 4, 4),
('The Pragmatic Programmer', 'Andrew Hunt & David Thomas', 'Technology', 5, 5),
('Code Complete', 'Steve McConnell', 'Technology', 2, 2),
('The Mythical Man-Month', 'Frederick P. Brooks Jr.', 'Technology', 3, 3),
('Introduction to Algorithms', 'Thomas H. Cormen', 'Technology', 2, 2),
('Design Patterns', 'Erich Gamma et al.', 'Technology', 3, 3),
('Refactoring', 'Martin Fowler', 'Technology', 3, 3),
('Clean Architecture', 'Robert C. Martin', 'Technology', 4, 4),
('Cracking the Coding Interview', 'Gayle Laakmann McDowell', 'Technology', 6, 6),
('Grokking Algorithms', 'Aditya Bhargava', 'Technology', 5, 5),
('Don''t Make Me Think', 'Steve Krug', 'Technology', 4, 4),
('Structure and Interpretation of Computer Programs', 'Harold Abelson', 'Technology', 2, 2),
('The C Programming Language', 'Brian W. Kernighan & Dennis M. Ritchie', 'Technology', 3, 3),
('Effective Java', 'Joshua Bloch', 'Technology', 3, 3),
('Python Crash Course', 'Eric Matthes', 'Technology', 5, 5),
('Designing Data-Intensive Applications', 'Martin Kleppmann', 'Technology', 4, 4),
('Algorithms to Live By', 'Brian Christian & Tom Griffiths', 'Technology', 3, 3),
('Hackers: Heroes of the Computer Revolution', 'Steven Levy', 'Technology', 2, 2),
('Superintelligence', 'Nick Bostrom', 'Technology', 3, 3),
('Life 3.0', 'Max Tegmark', 'Technology', 3, 3),

-- Thriller & Mystery
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Thriller', 4, 4),
('Gone Girl', 'Gillian Flynn', 'Thriller', 5, 5),
('The Da Vinci Code', 'Dan Brown', 'Thriller', 6, 6),
('Angels & Demons', 'Dan Brown', 'Thriller', 4, 4),
('And Then There Were None', 'Agatha Christie', 'Mystery', 5, 5),
('Murder on the Orient Express', 'Agatha Christie', 'Mystery', 4, 4),
('The Silence of the Lambs', 'Thomas Harris', 'Thriller', 3, 3),
('Shutter Island', 'Dennis Lehane', 'Thriller', 3, 3),
('The Girl on the Train', 'Paula Hawkins', 'Thriller', 5, 5),
('Big Little Lies', 'Liane Moriarty', 'Mystery', 4, 4),
('The Hound of the Baskervilles', 'Arthur Conan Doyle', 'Mystery', 6, 6),
('The Maltese Falcon', 'Dashiell Hammett', 'Mystery', 3, 3),
('Rebecca', 'Daphne du Maurier', 'Mystery', 4, 4),
('In Cold Blood', 'Truman Capote', 'True Crime', 3, 3),
('The Secret History', 'Donna Tartt', 'Mystery', 4, 4),

-- Historical & General Fiction
('The Book Thief', 'Markus Zusak', 'Historical Fiction', 5, 5),
('All the Light We Cannot See', 'Anthony Doerr', 'Historical Fiction', 4, 4),
('The Kite Runner', 'Khaled Hosseini', 'Historical Fiction', 6, 6),
('A Thousand Splendid Suns', 'Khaled Hosseini', 'Historical Fiction', 5, 5),
('The Alchemist', 'Paulo Coelho', 'Fiction', 7, 7),
('Life of Pi', 'Yann Martel', 'Fiction', 5, 5),
('Memoirs of a Geisha', 'Arthur Golden', 'Historical Fiction', 4, 4),
('The Handmaid''s Tale', 'Margaret Atwood', 'Dystopian', 5, 5),
('The Color Purple', 'Alice Walker', 'Historical Fiction', 3, 3),
('Beloved', 'Toni Morrison', 'Historical Fiction', 3, 3),
('One Hundred Years of Solitude', 'Gabriel García Márquez', 'Magical Realism', 4, 4),
('The Shadow of the Wind', 'Carlos Ruiz Zafón', 'Historical Fiction', 3, 3),
('Pillars of the Earth', 'Ken Follett', 'Historical Fiction', 2, 2),
('Wolf Hall', 'Hilary Mantel', 'Historical Fiction', 2, 2),
('The Nightingale', 'Kristin Hannah', 'Historical Fiction', 5, 5),
('Pachinko', 'Min Jin Lee', 'Historical Fiction', 4, 4),
('Where the Crawdads Sing', 'Delia Owens', 'Fiction', 6, 6),
('The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'Historical Fiction', 5, 5),
('Normal People', 'Sally Rooney', 'Fiction', 4, 4),
('The Midnight Library', 'Matt Haig', 'Fiction', 5, 5);